compatibility_date = "2022-04-05"
main = "index.ts"
name = "northwind-worker"
route = "api.northwind.d1sql.com/*"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_id = "8a2f773d-ca5e-426c-a6c3-df1efa312d0c" 
database_name = "northwind"
